# Generated by Django 5.2.8 on 2025-11-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='availability',
        ),
        migrations.AddField(
            model_name='barber',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barber',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
